ALTER TABLE `invoices` ADD `reminder_level` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE `recurring_series` ADD `state` text DEFAULT 'active' NOT NULL;--> statement-breakpoint
ALTER TABLE `recurring_series` ADD `total_count` integer;--> statement-breakpoint
ALTER TABLE `recurring_series` ADD `last_error` text;--> statement-breakpoint
-- Recurring templates become their own kind; "recurring_series_id" now only means "generated by".
UPDATE `invoices` SET `kind` = 'recurring_template', `recurring_series_id` = NULL WHERE `id` IN (SELECT `template_invoice_id` FROM `recurring_series`);--> statement-breakpoint
-- "void" was never set by the app; anything carrying it is a cancelled invoice.
UPDATE `invoices` SET `status` = 'cancelled' WHERE `status` = 'void';--> statement-breakpoint
-- Dunning state moves from the event log onto the invoice.
UPDATE `invoices` SET `reminder_level` = coalesce((SELECT max(json_extract(e.`detail`, '$.level')) FROM `invoice_events` e WHERE e.`invoice_id` = `invoices`.`id` AND e.`type` = 'reminder'), 0);--> statement-breakpoint
-- Series: one state instead of active/remaining/end_date.
UPDATE `recurring_series` SET
  `state` = CASE WHEN `remaining` = 0 THEN 'completed' WHEN `active` = 1 THEN 'active' ELSE 'paused' END,
  `total_count` = CASE WHEN `remaining` IS NULL THEN NULL ELSE `generated_count` + `remaining` END;--> statement-breakpoint
-- Snapshots frozen before these fields existed get them, so the type can require them.
UPDATE `invoices` SET `snapshot` = json_set(`snapshot`, '$.kind', `kind`) WHERE `snapshot` IS NOT NULL AND json_type(`snapshot`, '$.kind') IS NULL;--> statement-breakpoint
UPDATE `invoices` SET `snapshot` = json_set(`snapshot`, '$.relatedNumber', json('null')) WHERE `snapshot` IS NOT NULL AND json_type(`snapshot`, '$.relatedNumber') IS NULL;--> statement-breakpoint
UPDATE `invoices` SET `snapshot` = json_set(`snapshot`, '$.client.buyerReference', '') WHERE `snapshot` IS NOT NULL AND json_type(`snapshot`, '$.client.buyerReference') IS NULL;--> statement-breakpoint
-- Early drafts stored payment terms as a bare number of days; those are not terms text.
UPDATE `invoices` SET `payment_terms` = '' WHERE `payment_terms` <> '' AND `payment_terms` NOT GLOB '*[^0-9]*';
